name: PR

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

permissions:
  contents: write
  pull-requests: write
  packages: write
  id-token: write

jobs:
  determine_version:
    uses: ./.github/workflows/determine_version.yaml
  build:
    needs: determine_version
    uses: ./.github/workflows/build.yaml
    with:
      version: ${{ needs.determine_version.outputs.version }}
  native_build:
    needs: determine_version
    uses: ./.github/workflows/native_build.yaml
    with:
      version: ${{ needs.determine_version.outputs.version }}
  owasp:
    needs: determine_version
    uses: ./.github/workflows/owasp.yaml
    with:
      version: ${{ needs.determine_version.outputs.version }}
