name: Release

on:
  workflow_dispatch:
  release:
    types: [created]

defaults:
  run:
    shell: bash

permissions:
  contents: write
  pull-requests: write
  packages: write
  id-token: write

jobs:
  determine_version:
    uses: ./.github/workflows/determine_version.yaml
  build:
    needs: determine_version
    uses: ./.github/workflows/build.yaml
    with:
      version: ${{ needs.determine_version.outputs.version }}
      upload: true
      sign: true
  native_build:
    needs: determine_version
    uses: ./.github/workflows/native_build.yaml
    with:
      version: ${{ needs.determine_version.outputs.version }}
      upload: true
      sign: true
