name: Release
on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  determine_version:
    uses: ./.github/workflows/determine_version.yaml
  build:
    needs: determine_version
    uses: ./.github/workflows/build.yaml
    with:
      version: ${{ needs.determine_version.outputs.version }}
  native_build:
    needs: determine_version
    uses: ./.github/workflows/native_build.yaml
    with:
      version: ${{ needs.determine_version.outputs.version }}
